# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=5)),
                ('coordx', models.CharField(max_length=20)),
                ('coordy', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Posto com ótima classificação'), ('B', 'Posto com boa classificação'), ('C', 'Posto com média classificação'), ('D', 'Posto com baixa classificação')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('entry_date', models.DateField(null=True)),
                ('data_planejado', models.PositiveIntegerField(null=True)),
                ('data_realizado', models.PositiveIntegerField(null=True)),
                ('number', models.CharField(max_length=20, null=True)),
                ('resumo', models.TextField(null=True)),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='abastece.Base')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='abastece.Employee')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('encerrado', models.BooleanField(default=False)),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('data_atribuido', models.PositiveIntegerField(null=True)),
                ('data_fechado', models.PositiveIntegerField(null=True)),
                ('description', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrydate', models.PositiveIntegerField()),
                ('item_new', models.IntegerField()),
                ('item_used', models.IntegerField()),
                ('item_broaked', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=40, null=True)),
                ('maker', models.CharField(max_length=45, null=True)),
                ('width', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('depth', models.FloatField(null=True)),
                ('prazocompra', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemControlado',
            fields=[
                ('identificador', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=80, null=True)),
                ('assetnumber', models.CharField(max_length=80, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ModeloViatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
                ('km_rev', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MoveItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=60)),
                ('cgmp', models.CharField(max_length=5)),
                ('status_opc', models.BooleanField()),
                ('status_vip', models.BooleanField()),
                ('coordx', models.CharField(max_length=20)),
                ('coordy', models.CharField(max_length=20)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Base')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('in_time', models.PositiveIntegerField(null=True)),
                ('out_time', models.PositiveIntegerField(null=True)),
                ('entry_date', models.DateField(default='1970-01-01')),
                ('in_coordx', models.CharField(max_length=20, null=True)),
                ('in_coordy', models.CharField(max_length=20, null=True)),
                ('out_coordx', models.CharField(max_length=20, null=True)),
                ('out_coordy', models.CharField(max_length=20, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('status', models.IntegerField()),
                ('description', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=45)),
                ('start_date', models.PositiveIntegerField(null=True)),
                ('end_date', models.PositiveIntegerField(null=True)),
                ('start_coordx', models.CharField(max_length=20)),
                ('start_coordy', models.CharField(max_length=20)),
                ('end_coordx', models.CharField(max_length=20)),
                ('end_coordy', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Employee')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Posto')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('encerrado', models.BooleanField(default=False)),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('data_atribuido', models.PositiveIntegerField(null=True)),
                ('data_fechado', models.PositiveIntegerField(null=True)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('posto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='abastece.Posto')),
            ],
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('placa', models.CharField(max_length=7)),
                ('celular', models.CharField(max_length=11, null=True)),
                ('coordx', models.CharField(max_length=20, null=True)),
                ('coordy', models.CharField(max_length=20, null=True)),
                ('quilometragem', models.PositiveIntegerField(null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='abastece.Employee')),
                ('modeloviatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.ModeloViatura')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='posto',
            name='warehouse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='abastece.Warehouse'),
        ),
        migrations.AddField(
            model_name='moveitem',
            name='warehouse_dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='abastece.Warehouse'),
        ),
        migrations.AddField(
            model_name='moveitem',
            name='warehouse_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='abastece.Warehouse'),
        ),
        migrations.AddField(
            model_name='itemcontrolado',
            name='posto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='abastece.Posto'),
        ),
        migrations.AddField(
            model_name='itemcontrolado',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Warehouse'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Item'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Warehouse'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='posto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='abastece.Posto'),
        ),
        migrations.AddField(
            model_name='evento',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Form'),
        ),
        migrations.AddField(
            model_name='evento',
            name='posto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='abastece.Posto'),
        ),
        migrations.AddField(
            model_name='base',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Employee'),
        ),
        migrations.AddField(
            model_name='base',
            name='viatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Viatura'),
        ),
        migrations.AddField(
            model_name='base',
            name='warehouse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='abastece.Warehouse'),
        ),
    ]
