# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('name', models.CharField(max_length=5)),
                ('coordX', models.CharField(max_length=15)),
                ('coordY', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Posto com ótima classificação'), ('B', 'Posto com boa classificação'), ('C', 'Posto com média classificação'), ('D', 'Posto com baixa classificação')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('serial', models.CharField(max_length=80, unique=True)),
                ('assetnumber1', models.CharField(max_length=80, unique=True)),
                ('assetnumber2', models.CharField(max_length=80, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('data_planejado', models.PositiveIntegerField()),
                ('data_realizado', models.PositiveIntegerField()),
                ('number', models.CharField(max_length=15)),
                ('resumo', models.TextField(null=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Base')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloEquipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloViatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('name', models.CharField(max_length=15)),
                ('km_rev', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('name', models.CharField(max_length=60)),
                ('cgmp', models.CharField(max_length=5)),
                ('status_opc', models.BooleanField()),
                ('status_vip', models.BooleanField()),
                ('coordX', models.CharField(max_length=15)),
                ('coordY', models.CharField(max_length=15)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Base')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('timestamp', models.PositiveIntegerField()),
                ('tipo', models.BooleanField()),
                ('coordX', models.CharField(max_length=15)),
                ('coordY', models.CharField(max_length=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('placa', models.CharField(max_length=7)),
                ('celular', models.CharField(max_length=11)),
                ('coordX', models.CharField(max_length=15)),
                ('coordY', models.CharField(max_length=15)),
                ('quilometragem', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Employee')),
                ('modeloviatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.ModeloViatura')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='posto',
            name='warehouse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='abastece.Warehouse'),
        ),
        migrations.AddField(
            model_name='evento',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Form'),
        ),
        migrations.AddField(
            model_name='evento',
            name='posto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Posto'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='modeloequipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.ModeloEquipamento'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Warehouse'),
        ),
        migrations.AddField(
            model_name='base',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Employee'),
        ),
        migrations.AddField(
            model_name='base',
            name='viatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Viatura'),
        ),
        migrations.AddField(
            model_name='base',
            name='warehouse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='abastece.Warehouse'),
        ),
    ]
