# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('status', models.IntegerField()),
                ('description', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=45)),
                ('start_date', models.PositiveIntegerField(null=True)),
                ('end_date', models.PositiveIntegerField(null=True)),
                ('start_coordX', models.CharField(max_length=15)),
                ('start_coordY', models.CharField(max_length=15)),
                ('end_coordX', models.CharField(max_length=15)),
                ('end_coordY', models.CharField(max_length=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Employee')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Posto')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='abastece.Employee'),
        ),
    ]
