# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('encerrado', models.BooleanField(default=False)),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('data_atribuido', models.PositiveIntegerField(null=True)),
                ('data_fechado', models.PositiveIntegerField(null=True)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('posto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='abastece.Posto')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('encerrado', models.BooleanField(default=False)),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('data_atribuido', models.PositiveIntegerField(null=True)),
                ('data_fechado', models.PositiveIntegerField(null=True)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('posto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='abastece.Posto')),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='abastece.Base'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_planejado',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_realizado',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='entry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='posto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='abastece.Posto'),
        ),
    ]
