# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoEvento',
        ),
        migrations.AddField(
            model_name='itemcontrolado',
            name='posto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='abastece.Posto'),
        ),
    ]
