# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linhabase',
            name='posto_ok',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
