# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0002_auto_20170104_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viatura',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='abastece.Employee'),
        ),
    ]
