# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0003_auto_20161221_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='coordX',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='base',
            name='coordY',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='modeloviatura',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='posto',
            name='coordX',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='posto',
            name='coordY',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='punch',
            name='coordX',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='punch',
            name='coordY',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='description',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='end_coordX',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='end_coordY',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='start_coordX',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='start_coordY',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='coordX',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='coordY',
            field=models.CharField(max_length=20),
        ),
    ]
