# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0003_cronograma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='antena915',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='asbuilt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='icr',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='outro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='plano_verao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='preditiva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='preventiva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='retirada58',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='sinal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='suporte_angular',
            field=models.DateField(blank=True, null=True),
        ),
    ]
