# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0003_auto_20170118_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viatura',
            name='celular',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='coordx',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='coordy',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='quilometragem',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
