# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0004_auto_20161221_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='tipo',
            field=models.CharField(max_length=8),
        ),
    ]
