# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0004_auto_20170220_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronograma',
            name='data_entrada',
        ),
    ]
