# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0004_auto_20170118_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='entry_date',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
