# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0005_auto_20161221_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punch',
            name='active',
        ),
        migrations.RemoveField(
            model_name='punch',
            name='coordX',
        ),
        migrations.RemoveField(
            model_name='punch',
            name='coordY',
        ),
        migrations.RemoveField(
            model_name='punch',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='punch',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='punch',
            name='tipo',
        ),
    ]
