# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0005_remove_cronograma_data_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='data_entrada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
