# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0006_cronograma_data_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='antena915',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='asbuilt',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='icr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='outro',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='plano_verao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='preditiva',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='preventiva',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='retirada58',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='sinal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='suporte_angular',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
