# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0007_auto_20161221_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('in_time', models.PositiveIntegerField()),
                ('out_time', models.PositiveIntegerField()),
                ('entry_date', models.CharField(max_length=8)),
                ('in_coordx', models.CharField(max_length=20, null=True)),
                ('in_coordy', models.CharField(max_length=20, null=True)),
                ('out_coordx', models.CharField(max_length=20, null=True)),
                ('out_coordy', models.CharField(max_length=20, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abastece.Employee')),
            ],
        ),
    ]
