# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0007_auto_20170222_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronograma',
            name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='cronograma',
            name='posto',
        ),
        migrations.AddField(
            model_name='cronograma',
            name='posto_cgmp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='posto_nome',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
