# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0008_auto_20170222_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='data_ok',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
