# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0008_punch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='entry_date',
            field=models.CharField(max_length=10),
        ),
    ]
