# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0009_auto_20161222_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch',
            name='in_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='punch',
            name='out_time',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
