# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastece', '0010_auto_20161222_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punch',
            name='entry_date',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='analise',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
